apiVersion: v2
appVersion: 3.14.7-alpha2
description: BlueKing Configuration Management DataBase (bk-cmdb) is an enterprise level configuration management serivce database.
name: bk-cmdb-transferservice
type: application
version: 3.15.7-alpha2
