## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

## @param global.imageRegistry Global Docker image registry
## @param global.imagePullSecrets Global Docker registry secret names as an array
## @param global.storageClass Global StorageClass for Persistent Volume(s)
##
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: [ ]
  storageClass: ""
  # 加密算法类型，枚举值：CLASSIC（国际算法）、SHANGMI（国密算法）
  bkCryptoType: "CLASSIC"

## @section bk-cmdb image parameters
##

## bk-cmdb image parameters
## @param image.registry bk-cmdb image registry
## @param image.pullPolicy bk-cmdb image pull policy
## @param image.pullSecretName bk-cmdb image pull secret name
##docker-bkrepo.cwoa.net/h536b8/canway_d/blueking/cmdb_transferservice:v3.14.6-rc.1
image:
  registry: hub.bktencent.com
  pullPolicy: IfNotPresent
  pullSecretName: ""


## @section bk-cmdb transferservice parameters
##
transferservice:
  ## @param transferservice.enabled Enable transferservice deployment
  ##
  enabled: true
  ## bk-cmdb transferservice image parameters
  ## @param transferservice.image.repository bk-cmdb transferservice image repository
  ## @param transferservice.image.rag bk-cmdb transferservice image tag
  ##docker-bkrepo.cwoa.net/h536b8/canway_d/blueking/cmdb_transferservice:v3.14.6-rc.1
  image:
    repository: blueking/cmdb_transferservice
    #    repository: blueking/cmdb_transferservice
    tag:
  ## @param transferservice.replicas Number of transferservice replicas to deploy
  ##
  replicas: 1
  ## @param transferservice.port bk-cmdb transferservice service HTTP port
  ##
  annotations:
    kubernetes.io/ingress.class: nginx
  port: 80
  ## @param transferservice.workDir bk-cmdb transferservice work directory
  ##
  #  configPath: /data/cmdb/cmdb_transferservice/config.yaml
  workDir: /data/cmdb/cmdb_transferservice
  ## bk-cmdb transferservice start command parameters
  ## @param transferservice.command.logDir bk-cmdb transferservice log directory
  ## @param transferservice.command.logLevel bk-cmdb transferservice log level
  ## @param transferservice.command.logLevel Enable bk-cmdb transferservice print log to stderr
  ##
  command:
    logDir: /data/cmdb/cmdb_transferservice/logs
    ## @param if syncConfig value is not nil ,will use --sync-config=
    #  syncConfig: /data/cmdb/cmdb_transferservice/sync_conf.yaml
    syncConfig: /data/cmdb/cmdb_transferservice/sync_conf.yaml
    logLevel: 3
    logToStdErr: false

  ## @param podAnnotations Annotations for bk-panel pods
  ## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
  ##
  podAnnotations: { }
  ## @param affinity Affinity for pod assignment
  ## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ## NOTE: podAffinityPreset, podAntiAffinityPreset, and  nodeAffinityPreset will be ignored when it's set
  ##
  affinity: { }
  ## @param nodeSelector Node labels for pod assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: { }
  ## @param tolerations Tolerations for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
  ##
  tolerations: [ ]
  volumeMounts: [ ]
  volumes: [ ]
  ## bk-cmdb containers' resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ## @param resources.limits The resources limits for the bk-cmdb container
  ## @param resources.requests [object] The requested resources for the bk-cmdb container
  ##
  resources:
    limits:
      cpu: 200m
      memory: 1024Mi
    requests:
      memory: 512Mi
      cpu: 200m


## @section bk-cmdb config and service center parameters
##
configAndServiceCenter:
  addr: bk-zookeeper:2181
  tls:
    insecureSkipVerify: true
    caFile:
    certFile:
    keyFile:
    password:
