{{- if .Values.transferservice.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "bk-cmdb.transferservice" . }}"
spec:
  ports:
    - name: http
      port: 80
      targetPort: {{ .Values.transferservice.port }}
  selector:
    component: transferservice
{{- end }}
