{{- if .Values.transferservice.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ template "bk-cmdb.fullname" . }}-transferservice"
  labels:
    component: transferservice
spec:
  replicas: {{ .Values.transferservice.replicas }}
  selector:
    matchLabels:
      component: transferservice
  template:
    metadata:
      labels:
        values-hash: "{{ toYaml .Values | sha256sum | trunc 63 }}"
        component: transferservice
      {{- with .Values.transferservice.annotations }}
      annotations:
        {{ toYaml . | indent 8 }}
      {{- end }}
      {{- if .Values.transferservice.podAnnotations }}
        {{ toYaml .Values.transferservice.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- include "cmdb.imagePullSecrets" . | nindent 6 }}

      {{- if .Values.transferservice.command.syncConfig }}
      volumes:
        - name: sync-conf
          configMap:
            name: "{{ .Release.Name }}-configures"
            items:
              - key: sync_conf.yaml
                path: sync_conf.yaml
      {{ end }}

      containers:
        - name: transferservice
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          {{- if .Values.transferservice.env }}
            {{ toYaml .Values.transferservice.env | indent 10 }}
          {{- end }}

          image: {{ .Values.image.registry }}/{{ .Values.transferservice.image.repository }}:v{{ default .Chart.AppVersion .Values.transferservice.image.tag }}
          workingDir: {{ .Values.transferservice.workDir }}/
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{/*
          源环境：
          ./cmdb_transferservice --addrport=${服务监听地址} --regdiscv=${zk地址} --logtostderr=${是否把日志输出到stderr} --log-dir=${日志存放路径} --v=${日志级别}

          目标环境:新增--sync-config 配置
          ./cmdb_transferservice --sync-config=${CMDB同步服务额外配置}--addrport=${服务监听地址} --regdiscv=${zk地址} --logtostderr=${是否把日志输出到stderr} --log-dir=${日志存放路径} --v=${日志级别}
          */}}
          command:
            - "./cmdb_transferservice"
          args:
            - "--addrport=$(POD_IP):{{ .Values.transferservice.port }}"
        {{- if .Values.transferservice.command.logDir }}
            - --log-dir={{ .Values.transferservice.command.logDir }}
        {{- end }}

        {{- if .Values.transferservice.command.syncConfig }}
            - --sync-config={{ .Values.transferservice.command.syncConfig }}
        {{- end }}
            - --regdiscv={{ .Values.configAndServiceCenter.addr }}
            - --v={{ .Values.transferservice.command.logLevel }}
            - --logtostderr={{ .Values.transferservice.command.logToStdErr }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.transferservice.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.transferservice.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
          ports:
            - containerPort: {{ .Values.transferservice.port }}

        {{- if .Values.transferservice.command.syncConfig }}
          volumeMounts:
            - name: sync-conf
              mountPath: {{ .Values.transferservice.command.syncConfig }}
              subPath: sync_conf.yaml
        {{- end }}

        {{- with .Values.transferservice.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
        {{- end }}

{{- end }}
